FROM docker.io/debian:trixie-slim

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && sed -i 's/Components: main/Components: main contrib non-free/g' \
      /etc/apt/sources.list.d/debian.sources \
  && apt-get -yq update \
  && apt-get -yq dist-upgrade \
  && apt-get -yq install \
    --no-install-recommends \
      alsa-utils \
      bind9-dnsutils \
      ca-certificates \
      coreutils \
      curl \
      dbus-x11 \
      expect-dev \
      firefox-esr \
      gettext-base \
      iproute2 \
      iputils-ping \
      jq \
      libgl1-mesa-dri \
      locales \
      mesa-utils \
      mingetty \
      nano \
      net-tools \
      openssl \
      paprefs \
      pavucontrol \
      pulseaudio \
      sudo \
      systemd \
      systemd-sysv \
      tasksel \
      tigervnc-standalone-server \
      tzdata \
      udev \
      vim \
      wget \
      x11-utils \
      xz-utils \
      yq

RUN set -exu \
  && wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra.asc \
  && wget -O "/etc/apt/sources.list.d/xpra.sources" \
      https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/trixie/xpra-beta.sources \
  && apt-get -yq update \
  && apt-get -yq install \
      --no-install-recommends \
        xpra

RUN set -exu \
  && apt-get -yq clean

RUN set -exu \
  && ls /usr/lib/systemd/system/sysinit.target.wants/ | grep -v systemd-tmpfiles-setup | xargs -i{} rm -vf /usr/lib/systemd/system/sysinit.target.wants/{} \
  && rm -vf \
    /etc/systemd/system/*.wants/* \
    /usr/lib/systemd/system/anaconda.target.wants/* \
    /usr/lib/systemd/system/basic.target.wants/* \
    /usr/lib/systemd/system/local-fs.target.wants/* \
    /usr/lib/systemd/system/multi-user.target.wants/* \
    /usr/lib/systemd/system/plymouth* \
    /usr/lib/systemd/system/sockets.target.wants/*initctl* \
    /usr/lib/systemd/system/sockets.target.wants/*udev* \
    /usr/lib/systemd/system/systemd-update-utmp* \
  && systemctl daemon-reload

COPY rootfs /

RUN set -exu \
  && chmod +x /usr/local/sbin/init \
  && chmod +x /usr/local/sbin/fakegetty \
  && systemctl enable user-init \
  && systemctl --user --global enable display.service \
  && systemctl --user --global enable pulseaudio.service \
  && systemctl --user --global enable xfce4.service

WORKDIR /root
VOLUME ["/sys/fs/cgroup"]
ENTRYPOINT ["/usr/local/sbin/init"]
