name: Image Build

on:
  workflow_dispatch:
  push:
    tags: [v*]

env:
  IMAGE_NAME: ghcr.io/kubevda/vdimage-debian-trixie-xfce
  PLATFORMS: linux/amd64
  ARCHS: amd64
  VERSION: latest
  COSIGN_EXPERIMENTAL: 1

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    steps:
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: src/
          file: src/Containerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=local,src=/home/runner/.${{ env.IMAGE_NAME }}.buildx-cache
          cache-to: type=local,dest=/home/runner/.${{ env.IMAGE_NAME }}.buildx-cache
